# Generated by Django 5.2.13 on 2026-08-09 18:08

import django.core.validators
from django.db import migrations, models


BACKFILL_BATCH_SIZE = 1_000


def backfill_chat_change_sequences(apps, schema_editor):
    ChatMessage = apps.get_model("chat", "ChatMessage")
    Trip = apps.get_model("trips", "Trip")
    database_alias = schema_editor.connection.alias

    trip_ids = (
        ChatMessage.objects.using(database_alias)
        .order_by()
        .values_list("trip_id", flat=True)
        .distinct()
        .iterator()
    )
    for trip_id in trip_ids:
        sequence = 0
        pending = []
        messages = (
            ChatMessage.objects.using(database_alias)
            .filter(trip_id=trip_id)
            .order_by("updated_at", "id")
            .iterator(chunk_size=BACKFILL_BATCH_SIZE)
        )
        for message in messages:
            sequence += 1
            message.change_sequence = sequence
            pending.append(message)
            if len(pending) == BACKFILL_BATCH_SIZE:
                ChatMessage.objects.using(database_alias).bulk_update(
                    pending,
                    ["change_sequence"],
                    batch_size=BACKFILL_BATCH_SIZE,
                )
                pending = []

        if pending:
            ChatMessage.objects.using(database_alias).bulk_update(
                pending,
                ["change_sequence"],
                batch_size=BACKFILL_BATCH_SIZE,
            )

        Trip.objects.using(database_alias).filter(pk=trip_id).update(
            chat_change_sequence=sequence
        )


def reset_chat_change_sequences(apps, schema_editor):
    ChatMessage = apps.get_model("chat", "ChatMessage")
    Trip = apps.get_model("trips", "Trip")
    database_alias = schema_editor.connection.alias
    ChatMessage.objects.using(database_alias).update(change_sequence=0)
    Trip.objects.using(database_alias).update(chat_change_sequence=0)


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_chatmessage_ai_status_chatmessage_sender_kind"),
        ("trips", "0010_trip_chat_change_sequence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="change_sequence",
            field=models.PositiveBigIntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(9007199254740991)
                ],
            ),
        ),
        migrations.RunPython(
            backfill_chat_change_sequences,
            reset_chat_change_sequences,
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["trip", "change_sequence", "id"],
                name="chat_msg_trip_change_seq_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("change_sequence__gte", 0),
                    ("change_sequence__lte", 9007199254740991),
                ),
                name="chat_message_change_sequence_safe",
            ),
        ),
    ]
