# Generated by Django 5.2.13 on 2026-08-09 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0009_trip_budget_estimate_non_negative"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="chat_change_sequence",
            field=models.BigIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(9007199254740991),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("chat_change_sequence__gte", 0),
                    ("chat_change_sequence__lte", 9007199254740991),
                ),
                name="trip_chat_change_sequence_safe",
            ),
        ),
    ]
